# Generated by Django 4.2 on 2023-04-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AccessApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
