# Generated by Django 4.2 on 2023-04-30 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AccessApp", "0004_alter_app_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="task", name="date", field=models.DateField(default=None),
        ),
    ]
